
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
//
// THIS FILE IS AUTO GENERATED BY generate_metrics.py DO NOT MODIFY IT BY HAND.
//

namespace cpp impala
namespace java org.apache.impala.thrift

include "Metrics.thrift"

// All metadata associated with a metric. Used to instanciate metrics.
struct TMetricDef {
  1: optional string key
  2: optional Metrics.TMetricKind kind
  3: optional Metrics.TUnit units
  4: optional list<string> contexts
  5: optional string label
  6: optional string description
}

const map<string,TMetricDef> TMetricDefs =
{
  "admission-controller.agg-mem-reserved.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Resource Pool $0 Aggregate Mem Reserved", 
    "key": "admission-controller.agg-mem-reserved.$0", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Resource Pool $0 Aggregate Mem Reserved", 
    "units": Metrics.TUnit.NONE
  }, 
  "admission-controller.agg-num-queued.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Resource Pool $0 Aggregate Queue Size", 
    "key": "admission-controller.agg-num-queued.$0", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Resource Pool $0 Aggregate Queue Size", 
    "units": Metrics.TUnit.NONE
  }, 
  "admission-controller.agg-num-running.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Resource Pool $0 Aggregate Num Running", 
    "key": "admission-controller.agg-num-running.$0", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Resource Pool $0 Aggregate Num Running", 
    "units": Metrics.TUnit.NONE
  }, 
  "admission-controller.local-backend-mem-reserved.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Resource Pool $0 Mem Reserved by the backend coordinator", 
    "key": "admission-controller.local-backend-mem-reserved.$0", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Resource Pool $0 Coordinator Backend Mem Reserved", 
    "units": Metrics.TUnit.NONE
  }, 
  "admission-controller.local-backend-mem-usage.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Resource Pool $0 Coordinator Backend Mem Usage", 
    "key": "admission-controller.local-backend-mem-usage.$0", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Resource Pool $0 Coordinator Backend Mem Usage", 
    "units": Metrics.TUnit.NONE
  }, 
  "admission-controller.local-mem-admitted.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Resource Pool $0 Local Mem Admitted", 
    "key": "admission-controller.local-mem-admitted.$0", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Resource Pool $0 Local Mem Admitted", 
    "units": Metrics.TUnit.NONE
  }, 
  "admission-controller.local-num-admitted-running.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Resource Pool $0 Coordinator Backend Num Running", 
    "key": "admission-controller.local-num-admitted-running.$0", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Resource Pool $0 Coordinator Backend Num Running", 
    "units": Metrics.TUnit.NONE
  }, 
  "admission-controller.local-num-queued.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Resource Pool $0 Queue Size on the coordinator", 
    "key": "admission-controller.local-num-queued.$0", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Resource Pool $0 Coordinator Backend Queue Size", 
    "units": Metrics.TUnit.NONE
  }, 
  "admission-controller.pool-max-mem-resources.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Resource Pool $0 Configured Max Mem Resources", 
    "key": "admission-controller.pool-max-mem-resources.$0", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Resource Pool $0 Configured Max Mem Resources", 
    "units": Metrics.TUnit.NONE
  }, 
  "admission-controller.pool-max-queued.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Resource Pool $0 Configured Max Queued", 
    "key": "admission-controller.pool-max-queued.$0", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Resource Pool $0 Configured Max Queued", 
    "units": Metrics.TUnit.NONE
  }, 
  "admission-controller.pool-max-requests.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Resource Pool $0 Configured Max Requests", 
    "key": "admission-controller.pool-max-requests.$0", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Resource Pool $0 Configured Max Requests", 
    "units": Metrics.TUnit.NONE
  }, 
  "admission-controller.time-in-queue-ms.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Resource Pool $0 Time in Queue", 
    "key": "admission-controller.time-in-queue-ms.$0", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Resource Pool $0 Time in Queue", 
    "units": Metrics.TUnit.TIME_MS
  }, 
  "admission-controller.total-admitted.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Total number of requests admitted to pool $0", 
    "key": "admission-controller.total-admitted.$0", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Resource Pool $0 Total Admitted", 
    "units": Metrics.TUnit.UNIT
  }, 
  "admission-controller.total-dequeued.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Total number of requests dequeued in pool $0", 
    "key": "admission-controller.total-dequeued.$0", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Resource Pool $0 Total Dequeued", 
    "units": Metrics.TUnit.UNIT
  }, 
  "admission-controller.total-queued.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Total number of requests queued in pool $0", 
    "key": "admission-controller.total-queued.$0", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Resource Pool $0 Total Queued", 
    "units": Metrics.TUnit.UNIT
  }, 
  "admission-controller.total-rejected.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Total number of requests rejected in pool $0", 
    "key": "admission-controller.total-rejected.$0", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Resource Pool $0 Total Rejected", 
    "units": Metrics.TUnit.UNIT
  }, 
  "admission-controller.total-released.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Total number of requests that have completed and released resources in pool $0", 
    "key": "admission-controller.total-released.$0", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Resource Pool $0 Total Released", 
    "units": Metrics.TUnit.UNIT
  }, 
  "admission-controller.total-timed-out.$0": {
    "contexts": [
      "RESOURCE_POOL"
    ], 
    "description": "Total number of requests timed out waiting while queued in pool $0", 
    "key": "admission-controller.total-timed-out.$0", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Resource Pool $0 Total Timed Out", 
    "units": Metrics.TUnit.UNIT
  }, 
  "buffer-pool.clean-page-bytes": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total bytes of clean page memory cached in the buffer pool.", 
    "key": "buffer-pool.clean-page-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Buffer Pool Clean Page Bytes.", 
    "units": Metrics.TUnit.BYTES
  }, 
  "buffer-pool.clean-pages": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total number of clean pages cached in the buffer pool.", 
    "key": "buffer-pool.clean-pages", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Buffer Pool Clean Pages.", 
    "units": Metrics.TUnit.NONE
  }, 
  "buffer-pool.clean-pages-limit": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Limit on number of clean pages cached in the buffer pool.", 
    "key": "buffer-pool.clean-pages-limit", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Buffer Pool Clean Pages Limit.", 
    "units": Metrics.TUnit.BYTES
  }, 
  "buffer-pool.free-buffer-bytes": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total bytes of free buffer memory cached in the buffer pool.", 
    "key": "buffer-pool.free-buffer-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Buffer Pool Free Buffer Bytes.", 
    "units": Metrics.TUnit.BYTES
  }, 
  "buffer-pool.free-buffers": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total number of free buffers cached in the buffer pool.", 
    "key": "buffer-pool.free-buffers", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Buffer Pool Free Buffers.", 
    "units": Metrics.TUnit.NONE
  }, 
  "buffer-pool.limit": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Maximum allowed bytes allocated by the buffer pool.", 
    "key": "buffer-pool.limit", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Buffer Pool Allocated Memory Limit.", 
    "units": Metrics.TUnit.BYTES
  }, 
  "buffer-pool.reserved": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total bytes of buffers reserved by Impala subsystems", 
    "key": "buffer-pool.reserved", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Buffer Pool Total Reserved Memory.", 
    "units": Metrics.TUnit.BYTES
  }, 
  "buffer-pool.system-allocated": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total buffer memory currently allocated by the buffer pool.", 
    "key": "buffer-pool.system-allocated", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Buffer Pool Total Allocated Memory.", 
    "units": Metrics.TUnit.BYTES
  }, 
  "buffer-pool.unused-reservation-bytes": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total bytes of buffer reservations by Impala subsystems that are currently unused", 
    "key": "buffer-pool.unused-reservation-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Buffer Pool Unused Reservation Bytes.", 
    "units": Metrics.TUnit.BYTES
  }, 
  "catalog-server.topic-processing-time-s": {
    "contexts": [
      "CATALOGSERVER"
    ], 
    "description": "Catalog Server Topic Processing Time", 
    "key": "catalog-server.topic-processing-time-s", 
    "kind": Metrics.TMetricKind.STATS, 
    "label": "Catalog Server Topic Processing Time", 
    "units": Metrics.TUnit.TIME_S
  }, 
  "catalog.num-databases": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of databases in the catalog.", 
    "key": "catalog.num-databases", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Databases", 
    "units": Metrics.TUnit.NONE
  }, 
  "catalog.num-tables": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of tables in the catalog.", 
    "key": "catalog.num-tables", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Tables", 
    "units": Metrics.TUnit.NONE
  }, 
  "catalog.ready": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Indicates if the catalog is ready.", 
    "key": "catalog.ready", 
    "kind": Metrics.TMetricKind.PROPERTY, 
    "label": "Catalog Ready", 
    "units": Metrics.TUnit.NONE
  }, 
  "catalog.server.client-cache.clients-in-use": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of clients currently in use by the Catalog Server client cache.", 
    "key": "catalog.server.client-cache.clients-in-use", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Catalog Server Client Cache Clients In Use", 
    "units": Metrics.TUnit.NONE
  }, 
  "catalog.server.client-cache.total-clients": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The total number of clients in the Catalog Server client cache.", 
    "key": "catalog.server.client-cache.total-clients", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Catalog Server Client Cache Total Clients", 
    "units": Metrics.TUnit.NONE
  }, 
  "catalog.version": {
    "contexts": [
      "CATALOGSERVER"
    ], 
    "description": "The full version string of the Catalog Server.", 
    "key": "catalog.version", 
    "kind": Metrics.TMetricKind.PROPERTY, 
    "label": "Catalog Version", 
    "units": Metrics.TUnit.NONE
  }, 
  "cgroups-mgr.active-cgroups": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of cgroups currently registered with the Cgroups Manager", 
    "key": "cgroups-mgr.active-cgroups", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Cgroups Manager Active Cgroups", 
    "units": Metrics.TUnit.UNIT
  }, 
  "external-data-source.class-cache.hits": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Number of cache hits in the External Data Source Class Cache", 
    "key": "external-data-source.class-cache.hits", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "External Data Source Class Cache Hits", 
    "units": Metrics.TUnit.UNIT
  }, 
  "external-data-source.class-cache.misses": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Number of cache misses in the External Data Source Class Cache", 
    "key": "external-data-source.class-cache.misses", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "External Data Source Class Cache Misses", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala-server.backends.client-cache.clients-in-use": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of active Impala Backend clients. These clients are for communication with other Impala Daemons.", 
    "key": "impala-server.backends.client-cache.clients-in-use", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Impala Backend Active Clients", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.backends.client-cache.total-clients": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The total number of Impala Backend clients in this Impala Daemon's client cache. These clients are for communication with other Impala Daemons.", 
    "key": "impala-server.backends.client-cache.total-clients", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Impala Backend Total Clients", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.ddl-durations-ms": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Distribution of DDL operation latencies", 
    "key": "impala-server.ddl-durations-ms", 
    "kind": Metrics.TMetricKind.HISTOGRAM, 
    "label": "DDL latency distribution", 
    "units": Metrics.TUnit.TIME_MS
  }, 
  "impala-server.hash-table.total-bytes": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The current size of all allocated hash tables.", 
    "key": "impala-server.hash-table.total-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Hash Tables Size", 
    "units": Metrics.TUnit.BYTES
  }, 
  "impala-server.hedged-read-ops": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The total number of hedged reads attempted over the life of the process", 
    "key": "impala-server.hedged-read-ops", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Hedged Read Operations", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala-server.hedged-read-ops-win": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The total number of times hedged reads were faster than regular read operations", 
    "key": "impala-server.hedged-read-ops-win", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Hedged Read Operations Won", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala-server.io-mgr.bytes-read": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The total number of bytes read by the IO manager.", 
    "key": "impala-server.io-mgr.bytes-read", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Impala Server Io Mgr Bytes Read", 
    "units": Metrics.TUnit.BYTES
  }, 
  "impala-server.io-mgr.bytes-written": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total number of bytes written to disk by the IO manager.", 
    "key": "impala-server.io-mgr.bytes-written", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Impala Server Io Mgr Bytes Written", 
    "units": Metrics.TUnit.BYTES
  }, 
  "impala-server.io-mgr.cached-bytes-read": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total number of cached bytes read by the IO manager.", 
    "key": "impala-server.io-mgr.cached-bytes-read", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Impala Server Io Mgr Cached Bytes Read", 
    "units": Metrics.TUnit.BYTES
  }, 
  "impala-server.io-mgr.local-bytes-read": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total number of local bytes read by the IO manager.", 
    "key": "impala-server.io-mgr.local-bytes-read", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Impala Server Io Mgr Local Bytes Read", 
    "units": Metrics.TUnit.BYTES
  }, 
  "impala-server.io-mgr.num-buffers": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of allocated IO buffers. IO buffers are shared by all queries.", 
    "key": "impala-server.io-mgr.num-buffers", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "IO Buffers", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.io-mgr.num-open-files": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The current number of files opened by the IO Manager", 
    "key": "impala-server.io-mgr.num-open-files", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Open Files", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.io-mgr.num-unused-buffers": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of unused IO buffers. IO buffers are shared by all queries.", 
    "key": "impala-server.io-mgr.num-unused-buffers", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Unused IO Buffers", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.io-mgr.short-circuit-bytes-read": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total number of short-circuit bytes read by the IO manager.", 
    "key": "impala-server.io-mgr.short-circuit-bytes-read", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Impala Server Io Mgr Short Circuit Bytes Read", 
    "units": Metrics.TUnit.BYTES
  }, 
  "impala-server.io-mgr.total-bytes": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Number of bytes used by IO buffers (used and unused).", 
    "key": "impala-server.io-mgr.total-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "IO Buffers Total Size", 
    "units": Metrics.TUnit.BYTES
  }, 
  "impala-server.io.mgr.cached-file-handles-hit-count": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Number of cache hits for cached HDFS file handles", 
    "key": "impala-server.io.mgr.cached-file-handles-hit-count", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "HDFS cached file handles hit count", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.io.mgr.cached-file-handles-hit-ratio": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "HDFS file handle cache hit ratio, between 0 and 1, where 1 means all reads were served from cached file handles.", 
    "key": "impala-server.io.mgr.cached-file-handles-hit-ratio", 
    "kind": Metrics.TMetricKind.STATS, 
    "label": "HDFS file handle cache hit ratio", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.io.mgr.cached-file-handles-miss-count": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Number of cache misses for cached HDFS file handles", 
    "key": "impala-server.io.mgr.cached-file-handles-miss-count", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "HDFS cached file handles miss count", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.io.mgr.num-cached-file-handles": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Number of currently cached HDFS file handles in the IO manager.", 
    "key": "impala-server.io.mgr.num-cached-file-handles", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Number of cached HDFS file handles", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.io.mgr.num-file-handles-outstanding": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Number of HDFS file handles that are currently in use by readers.", 
    "key": "impala-server.io.mgr.num-file-handles-outstanding", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Number of outstanding HDFS file handles", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.mem-pool.total-bytes": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The current size of the memory pool shared by all queries", 
    "key": "impala-server.mem-pool.total-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Memory Pool Size", 
    "units": Metrics.TUnit.BYTES
  }, 
  "impala-server.num-files-open-for-insert": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of HDFS files currently open for writing.", 
    "key": "impala-server.num-files-open-for-insert", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Files Open For Insert", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.num-fragments": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The total number of query fragments processed over the life of the process.", 
    "key": "impala-server.num-fragments", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Query Fragments", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala-server.num-fragments-in-flight": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of query fragments currently executing.", 
    "key": "impala-server.num-fragments-in-flight", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Query Fragments", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala-server.num-open-beeswax-sessions": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of open Beeswax sessions.", 
    "key": "impala-server.num-open-beeswax-sessions", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Beeswax Sessions", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.num-open-hiveserver2-sessions": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of open HiveServer2 sessions.", 
    "key": "impala-server.num-open-hiveserver2-sessions", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "HiveServer2 Sessions", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.num-queries": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The total number of queries processed over the life of the process", 
    "key": "impala-server.num-queries", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Queries", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala-server.num-queries-expired": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Number of queries expired due to inactivity.", 
    "key": "impala-server.num-queries-expired", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Queries Expired", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala-server.num-queries-registered": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The total number of queries registered on this Impala server instance. Includes queries that are in flight and waiting to be closed", 
    "key": "impala-server.num-queries-registered", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Queries Registered", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala-server.num-queries-spilled": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Number of queries for which any operator spilled.", 
    "key": "impala-server.num-queries-spilled", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Impala Server Num Queries Spilled", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala-server.num-sessions-expired": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Number of sessions expired due to inactivity.", 
    "key": "impala-server.num-sessions-expired", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Sessions Expired", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala-server.query-durations-ms": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Distribution of query latencies", 
    "key": "impala-server.query-durations-ms", 
    "kind": Metrics.TMetricKind.HISTOGRAM, 
    "label": "Query latency distribution", 
    "units": Metrics.TUnit.TIME_MS
  }, 
  "impala-server.ready": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Indicates if the Impala Server is ready.", 
    "key": "impala-server.ready", 
    "kind": Metrics.TMetricKind.PROPERTY, 
    "label": "Impala Server Ready", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.resultset-cache.total-bytes": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total number of bytes consumed for rows cached to support HS2 FETCH_FIRST.", 
    "key": "impala-server.resultset-cache.total-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Impala Server Resultset Cache Total Bytes", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.resultset-cache.total-num-rows": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total number of rows cached to support HS2 FETCH_FIRST.", 
    "key": "impala-server.resultset-cache.total-num-rows", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Impala Server Resultset Cache Total Num Rows", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala-server.scan-ranges.num-missing-volume-id": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The total number of scan ranges read over the life of the process that did not have volume metadata", 
    "key": "impala-server.scan-ranges.num-missing-volume-id", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Scan Ranges Missing Volume Information", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala-server.scan-ranges.total": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The total number of scan ranges read over the life of the process", 
    "key": "impala-server.scan-ranges.total", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Scan Ranges", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala-server.version": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The full version string of the Impala Server.", 
    "key": "impala-server.version", 
    "kind": Metrics.TMetricKind.PROPERTY, 
    "label": "Impala Server Version", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala.thrift-server.CatalogService.connection-setup-queue-size": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of connections to the Catalog Service that have been accepted and are waiting to be setup.", 
    "key": "impala.thrift-server.CatalogService.connection-setup-queue-size", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Catalog Service Connections Queued for Setup", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala.thrift-server.CatalogService.connections-in-use": {
    "contexts": [
      "CATALOGSERVER"
    ], 
    "description": "The number of active catalog service connections to this Catalog Server.", 
    "key": "impala.thrift-server.CatalogService.connections-in-use", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Catalog Service Active Connections", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala.thrift-server.CatalogService.total-connections": {
    "contexts": [
      "CATALOGSERVER"
    ], 
    "description": "The total number of connections made to this Catalog Server's catalog service  over its lifetime.", 
    "key": "impala.thrift-server.CatalogService.total-connections", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Catalog Service Total Connections", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala.thrift-server.StatestoreService.connection-setup-queue-size": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of connections to the Statestore Service that have been accepted and are waiting to be setup.", 
    "key": "impala.thrift-server.StatestoreService.connection-setup-queue-size", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Statestore Service Connections Queued for Setup", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala.thrift-server.StatestoreService.connections-in-use": {
    "contexts": [
      "STATESTORE"
    ], 
    "description": "The number of active connections to this StateStore's StateStore service.", 
    "key": "impala.thrift-server.StatestoreService.connections-in-use", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "StateStore Service Active Connections", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala.thrift-server.StatestoreService.total-connections": {
    "contexts": [
      "STATESTORE"
    ], 
    "description": "The total number of connections made to this StateStore's StateStore service over its lifetime.", 
    "key": "impala.thrift-server.StatestoreService.total-connections", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "StateStore Service Connections", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala.thrift-server.backend.connection-setup-queue-size": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of connections to the Impala Backend Server that have been accepted and are waiting to be setup.", 
    "key": "impala.thrift-server.backend.connection-setup-queue-size", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Impala Backend Server Connections Queued for Setup", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala.thrift-server.backend.connections-in-use": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of active Impala Backend client connections to this Impala Daemon.", 
    "key": "impala.thrift-server.backend.connections-in-use", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Impala Backend Server Active Connections", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala.thrift-server.backend.total-connections": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The total number of Impala Backend client connections made to this Impala Daemon over its lifetime.", 
    "key": "impala.thrift-server.backend.total-connections", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Impala Backend Server Connections", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala.thrift-server.beeswax-frontend.connection-setup-queue-size": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of Beeswax API connections to this Impala Daemon that have been accepted and are waiting to be setup.", 
    "key": "impala.thrift-server.beeswax-frontend.connection-setup-queue-size", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Beeswax API Connections Queued for Setup", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala.thrift-server.beeswax-frontend.connections-in-use": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of active Beeswax API connections to this Impala Daemon.", 
    "key": "impala.thrift-server.beeswax-frontend.connections-in-use", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Beeswax API Active Connections", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala.thrift-server.beeswax-frontend.total-connections": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The total number of Beeswax API connections made to this Impala Daemon over its lifetime.", 
    "key": "impala.thrift-server.beeswax-frontend.total-connections", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Beeswax API Total Connections", 
    "units": Metrics.TUnit.UNIT
  }, 
  "impala.thrift-server.hiveserver2-frontend.connection-setup-queue-size": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of HiveServer2 API connections to this Impala Daemon that have been accepted and are waiting to be setup.", 
    "key": "impala.thrift-server.hiveserver2-frontend.connection-setup-queue-size", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "HiveServer2 API Connections Queued for Setup", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala.thrift-server.hiveserver2-frontend.connections-in-use": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of active HiveServer2 API connections to this Impala Daemon.", 
    "key": "impala.thrift-server.hiveserver2-frontend.connections-in-use", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "HiveServer2 API Active Connections", 
    "units": Metrics.TUnit.NONE
  }, 
  "impala.thrift-server.hiveserver2-frontend.total-connections": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The total number of HiveServer2 API connections made to this Impala Daemon over its lifetime.", 
    "key": "impala.thrift-server.hiveserver2-frontend.total-connections", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "HiveServer2 API Total Connections", 
    "units": Metrics.TUnit.UNIT
  }, 
  "jvm.$0.committed-usage-bytes": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Jvm $0 Committed Usage Bytes", 
    "key": "jvm.$0.committed-usage-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Jvm $0 Committed Usage Bytes", 
    "units": Metrics.TUnit.BYTES
  }, 
  "jvm.$0.current-usage-bytes": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Jvm $0 Current Usage Bytes", 
    "key": "jvm.$0.current-usage-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Jvm $0 Current Usage Bytes", 
    "units": Metrics.TUnit.BYTES
  }, 
  "jvm.$0.init-usage-bytes": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Jvm $0 Init Usage Bytes", 
    "key": "jvm.$0.init-usage-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Jvm $0 Init Usage Bytes", 
    "units": Metrics.TUnit.BYTES
  }, 
  "jvm.$0.max-usage-bytes": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Jvm $0 Max Usage Bytes", 
    "key": "jvm.$0.max-usage-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Jvm $0 Max Usage Bytes", 
    "units": Metrics.TUnit.BYTES
  }, 
  "jvm.$0.peak-committed-usage-bytes": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Jvm $0 Peak Committed Usage Bytes", 
    "key": "jvm.$0.peak-committed-usage-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Jvm $0 Peak Committed Usage Bytes", 
    "units": Metrics.TUnit.BYTES
  }, 
  "jvm.$0.peak-current-usage-bytes": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Jvm $0 Peak Current Usage Bytes", 
    "key": "jvm.$0.peak-current-usage-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Jvm $0 Peak Current Usage Bytes", 
    "units": Metrics.TUnit.BYTES
  }, 
  "jvm.$0.peak-init-usage-bytes": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Jvm $0 Peak Init Usage Bytes", 
    "key": "jvm.$0.peak-init-usage-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Jvm $0 Peak Init Usage Bytes", 
    "units": Metrics.TUnit.BYTES
  }, 
  "jvm.$0.peak-max-usage-bytes": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Jvm $0 Peak Max Usage Bytes", 
    "key": "jvm.$0.peak-max-usage-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Jvm $0 Peak Max Usage Bytes", 
    "units": Metrics.TUnit.BYTES
  }, 
  "kudu-client.version": {
    "contexts": [
      "IMPALAD", 
      "CATALOGSERVER", 
      "STATESTORE"
    ], 
    "description": "A version string identifying the Kudu client", 
    "key": "kudu-client.version", 
    "kind": Metrics.TMetricKind.PROPERTY, 
    "label": "Kudu Client Version", 
    "units": Metrics.TUnit.NONE
  }, 
  "mem-tracker.process.bytes-freed-by-last-gc": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The amount of memory freed by the last memory tracker garbage collection.", 
    "key": "mem-tracker.process.bytes-freed-by-last-gc", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "MemTracker Bytes Freed By Last Garbage Collection", 
    "units": Metrics.TUnit.BYTES
  }, 
  "mem-tracker.process.bytes-over-limit": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The amount of memory by which the process was over its memory limit the last time the memory limit was encountered.", 
    "key": "mem-tracker.process.bytes-over-limit", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "MemTracker Bytes Over Limit", 
    "units": Metrics.TUnit.BYTES
  }, 
  "mem-tracker.process.limit": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The process memory tracker limit.", 
    "key": "mem-tracker.process.limit", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Process Tracker Limit", 
    "units": Metrics.TUnit.BYTES
  }, 
  "mem-tracker.process.num-gcs": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The total number of garbage collections performed by the memory tracker over the life of the process.", 
    "key": "mem-tracker.process.num-gcs", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "MemTracker Garbage Collections", 
    "units": Metrics.TUnit.UNIT
  }, 
  "memory.anon-huge-page-bytes": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Total bytes of anonymous (a.k.a. transparent) huge pages used by this process.", 
    "key": "memory.anon-huge-page-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Anonymous Huge Pages.", 
    "units": Metrics.TUnit.BYTES
  }, 
  "memory.mapped-bytes": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Total bytes of memory mappings in this process (the virtual memory size).", 
    "key": "memory.mapped-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Total Virtual Memory.", 
    "units": Metrics.TUnit.BYTES
  }, 
  "memory.num-maps": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Total number of memory mappings in this process.", 
    "key": "memory.num-maps", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Number of memory mappings.", 
    "units": Metrics.TUnit.NONE
  }, 
  "memory.rss": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Resident set size (RSS) of this process, including TCMalloc, buffer pool and Jvm.", 
    "key": "memory.rss", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Resident set size.", 
    "units": Metrics.TUnit.BYTES
  }, 
  "memory.thp.defrag": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "The system-wide 'defrag' setting for Transparent Huge Pages.", 
    "key": "memory.thp.defrag", 
    "kind": Metrics.TMetricKind.PROPERTY, 
    "label": "Transparent Huge Pages Defrag Enabled.", 
    "units": Metrics.TUnit.NONE
  }, 
  "memory.thp.enabled": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "The system-wide 'enabled' setting for Transparent Huge Pages.", 
    "key": "memory.thp.enabled", 
    "kind": Metrics.TMetricKind.PROPERTY, 
    "label": "Transparent Huge Pages Enabled.", 
    "units": Metrics.TUnit.NONE
  }, 
  "memory.thp.khugepaged-defrag": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "The system-wide 'defrag' setting for khugepaged.", 
    "key": "memory.thp.khugepaged-defrag", 
    "kind": Metrics.TMetricKind.PROPERTY, 
    "label": "Khugepaged Defrag Enabled.", 
    "units": Metrics.TUnit.NONE
  }, 
  "memory.total-used": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Total memory currently used by TCMalloc and buffer pool.", 
    "key": "memory.total-used", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Total Used Memory.", 
    "units": Metrics.TUnit.BYTES
  }, 
  "process-start-time": {
    "contexts": [
      "IMPALAD", 
      "CATALOGSERVER", 
      "STATESTORE"
    ], 
    "description": "The local start time of the process", 
    "key": "process-start-time", 
    "kind": Metrics.TMetricKind.PROPERTY, 
    "label": "Process Start Time", 
    "units": Metrics.TUnit.NONE
  }, 
  "request-pool-service.resolve-pool-duration-ms": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Time (ms) spent resolving request request pools.", 
    "key": "request-pool-service.resolve-pool-duration-ms", 
    "kind": Metrics.TMetricKind.STATS, 
    "label": "Request Pool Service Resolve Pool Duration Ms", 
    "units": Metrics.TUnit.TIME_MS
  }, 
  "rpc-method.$0.call_duration": {
    "contexts": [
      "CATALOGSERVER", 
      "STATESTORE", 
      "IMPALAD"
    ], 
    "description": "Duration (ms) of RPC calls to $0", 
    "key": "rpc-method.$0.call_duration", 
    "kind": Metrics.TMetricKind.HISTOGRAM, 
    "label": "$0 RPC Call Duration", 
    "units": Metrics.TUnit.TIME_MS
  }, 
  "sanitizer-total-bytes-allocated": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Bytes allocated from the sanitizer malloc (Sanitizer debug builds only)", 
    "key": "sanitizer-total-bytes-allocated", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Sanitizer Malloc Bytes Allocated", 
    "units": Metrics.TUnit.BYTES
  }, 
  "senders-blocked-on-recvr-creation": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Number of senders waiting for receiving fragment to initialize", 
    "key": "senders-blocked-on-recvr-creation", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Number of senders waiting for receiving fragment to initialize.", 
    "units": Metrics.TUnit.NONE
  }, 
  "simple-scheduler.assignments.total": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of assignments", 
    "key": "simple-scheduler.assignments.total", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Assignments", 
    "units": Metrics.TUnit.UNIT
  }, 
  "simple-scheduler.initialized": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Indicates whether the scheduler has been initialized.", 
    "key": "simple-scheduler.initialized", 
    "kind": Metrics.TMetricKind.PROPERTY, 
    "label": "Simple Scheduler Initialized", 
    "units": Metrics.TUnit.NONE
  }, 
  "simple-scheduler.local-assignments.total": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Number of assignments operating on local data", 
    "key": "simple-scheduler.local-assignments.total", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Local Assignments", 
    "units": Metrics.TUnit.UNIT
  }, 
  "simple-scheduler.num-backends": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of backend connections from this Impala Daemon to other Impala Daemons.", 
    "key": "simple-scheduler.num-backends", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Backend Connections", 
    "units": Metrics.TUnit.NONE
  }, 
  "statestore-subscriber.connected": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Whether the Impala Daemon considers itself connected to the StateStore.", 
    "key": "statestore-subscriber.connected", 
    "kind": Metrics.TMetricKind.PROPERTY, 
    "label": "StateStore Connectivity", 
    "units": Metrics.TUnit.NONE
  }, 
  "statestore-subscriber.heartbeat-interval-time": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "The time (sec) between Statestore heartbeats.", 
    "key": "statestore-subscriber.heartbeat-interval-time", 
    "kind": Metrics.TMetricKind.STATS, 
    "label": "Statestore Subscriber Heartbeat Interval Time", 
    "units": Metrics.TUnit.TIME_S
  }, 
  "statestore-subscriber.last-recovery-duration": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "The amount of time the StateStore subscriber took to recover the connection the last time it was lost.", 
    "key": "statestore-subscriber.last-recovery-duration", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "StateStore Subscriber Last Recovery Duration", 
    "units": Metrics.TUnit.NONE
  }, 
  "statestore-subscriber.last-recovery-time": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "The local time that the last statestore recovery happened.", 
    "key": "statestore-subscriber.last-recovery-time", 
    "kind": Metrics.TMetricKind.PROPERTY, 
    "label": "Statestore Subscriber Last Recovery Time", 
    "units": Metrics.TUnit.NONE
  }, 
  "statestore-subscriber.registration-id": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "The most recent registration ID for this subscriber with the statestore. Set to 'N/A' if no registration has been completed", 
    "key": "statestore-subscriber.registration-id", 
    "kind": Metrics.TMetricKind.PROPERTY, 
    "label": "Statestore Subscriber Registration Id", 
    "units": Metrics.TUnit.NONE
  }, 
  "statestore-subscriber.statestore.client-cache.clients-in-use": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "The number of active StateStore subscriber clients in this Impala Daemon's client cache. These clients are for communication from this role to the StateStore.", 
    "key": "statestore-subscriber.statestore.client-cache.clients-in-use", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "StateStore Subscriber Active Clients", 
    "units": Metrics.TUnit.NONE
  }, 
  "statestore-subscriber.statestore.client-cache.total-clients": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "The total number of StateStore subscriber clients in this Impala Daemon's client cache. These clients are for communication from this role to the StateStore.", 
    "key": "statestore-subscriber.statestore.client-cache.total-clients", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "StateStore Subscriber Total Clients", 
    "units": Metrics.TUnit.NONE
  }, 
  "statestore-subscriber.topic-$0.processing-time-s": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Statestore Subscriber Topic $0 Processing Time", 
    "key": "statestore-subscriber.topic-$0.processing-time-s", 
    "kind": Metrics.TMetricKind.STATS, 
    "label": "Statestore Subscriber Topic $0 Processing Time", 
    "units": Metrics.TUnit.TIME_S
  }, 
  "statestore-subscriber.topic-update-duration": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "The time (sec) taken to process Statestore subcriber topic updates.", 
    "key": "statestore-subscriber.topic-update-duration", 
    "kind": Metrics.TMetricKind.STATS, 
    "label": "Statestore Subscriber Topic Update Duration", 
    "units": Metrics.TUnit.TIME_S
  }, 
  "statestore-subscriber.topic-update-interval-time": {
    "contexts": [
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "The time (sec) between Statestore subscriber topic updates.", 
    "key": "statestore-subscriber.topic-update-interval-time", 
    "kind": Metrics.TMetricKind.STATS, 
    "label": "Statestore Subscriber Topic Update Interval Time", 
    "units": Metrics.TUnit.TIME_S
  }, 
  "statestore.heartbeat-durations": {
    "contexts": [
      "STATESTORE"
    ], 
    "description": "The time (sec) spent sending heartbeat RPCs. Includes subscriber-side processing time and network transmission time.", 
    "key": "statestore.heartbeat-durations", 
    "kind": Metrics.TMetricKind.STATS, 
    "label": "Statestore Heartbeat Durations", 
    "units": Metrics.TUnit.TIME_S
  }, 
  "statestore.live-backends": {
    "contexts": [
      "STATESTORE"
    ], 
    "description": "The number of registered Statestore subscribers.", 
    "key": "statestore.live-backends", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Statestore Live Backends", 
    "units": Metrics.TUnit.NONE
  }, 
  "statestore.live-backends.list": {
    "contexts": [
      "STATESTORE"
    ], 
    "description": "The set of all live Statestore subscribers.", 
    "key": "statestore.live-backends.list", 
    "kind": Metrics.TMetricKind.SET, 
    "label": "Statestore Live Backends List", 
    "units": Metrics.TUnit.NONE
  }, 
  "statestore.topic-update-durations": {
    "contexts": [
      "STATESTORE"
    ], 
    "description": "The time (sec) spent sending topic update RPCs. Includes subscriber-side processing time and network transmission time.", 
    "key": "statestore.topic-update-durations", 
    "kind": Metrics.TMetricKind.STATS, 
    "label": "Statestore Topic Update Durations", 
    "units": Metrics.TUnit.TIME_S
  }, 
  "statestore.total-key-size-bytes": {
    "contexts": [
      "STATESTORE"
    ], 
    "description": "The sum of the size of all keys for all topics tracked by the StateStore.", 
    "key": "statestore.total-key-size-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Topic Key Size", 
    "units": Metrics.TUnit.NONE
  }, 
  "statestore.total-topic-size-bytes": {
    "contexts": [
      "STATESTORE"
    ], 
    "description": "The sum of the size of all keys and all values for all topics tracked by the StateStore.", 
    "key": "statestore.total-topic-size-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Topic Size", 
    "units": Metrics.TUnit.NONE
  }, 
  "statestore.total-value-size-bytes": {
    "contexts": [
      "STATESTORE"
    ], 
    "description": "The sum of the size of all values for all topics tracked by the StateStore.", 
    "key": "statestore.total-value-size-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Topic Value Size", 
    "units": Metrics.TUnit.NONE
  }, 
  "statestore.version": {
    "contexts": [
      "STATESTORE"
    ], 
    "description": "The full version string of the Statestore Server.", 
    "key": "statestore.version", 
    "kind": Metrics.TMetricKind.PROPERTY, 
    "label": "Statestore Version", 
    "units": Metrics.TUnit.NONE
  }, 
  "subscriber-heartbeat.client-cache.clients-in-use": {
    "contexts": [
      "STATESTORE"
    ], 
    "description": "The number of clients in use by the Statestore heartbeat client cache.", 
    "key": "subscriber-heartbeat.client-cache.clients-in-use", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Subscriber Heartbeat Client Cache Clients In Use", 
    "units": Metrics.TUnit.NONE
  }, 
  "subscriber-heartbeat.client-cache.total-clients": {
    "contexts": [
      "STATESTORE"
    ], 
    "description": "The total number of clients in the Statestore heartbeat client cache.", 
    "key": "subscriber-heartbeat.client-cache.total-clients", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Subscriber Heartbeat Client Cache Total Clients", 
    "units": Metrics.TUnit.NONE
  }, 
  "subscriber-update-state.client-cache.clients-in-use": {
    "contexts": [
      "STATESTORE"
    ], 
    "description": "The number of clients in use by the Statestore update state client cache.", 
    "key": "subscriber-update-state.client-cache.clients-in-use", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Subscriber Update State Client Cache Clients In Use", 
    "units": Metrics.TUnit.NONE
  }, 
  "subscriber-update-state.client-cache.total-clients": {
    "contexts": [
      "STATESTORE"
    ], 
    "description": "The total number of clients in the Statestore update state client cache.", 
    "key": "subscriber-update-state.client-cache.total-clients", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Subscriber Update State Client Cache Total Clients", 
    "units": Metrics.TUnit.NONE
  }, 
  "tcmalloc.bytes-in-use": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Number of bytes used by the application. This will not typically match the memory use reported by the OS, because it does not include TCMalloc overhead or memory fragmentation.", 
    "key": "tcmalloc.bytes-in-use", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "TCMalloc Bytes in Use", 
    "units": Metrics.TUnit.BYTES
  }, 
  "tcmalloc.pageheap-free-bytes": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Number of bytes in free, mapped pages in page heap. These bytes can be used to fulfill allocation requests. They always count towards virtual memory usage, and unless the underlying memory is swapped out by the OS, they also count towards physical memory usage.", 
    "key": "tcmalloc.pageheap-free-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "TCMalloc Pageheap Free", 
    "units": Metrics.TUnit.BYTES
  }, 
  "tcmalloc.pageheap-unmapped-bytes": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Number of bytes in free, unmapped pages in page heap. These are bytes that have been released back to the OS, possibly by one of the MallocExtension \"Release\" calls. They can be used to fulfill allocation requests, but typically incur a page fault. They always count towards virtual memory usage, and depending on the OS, typically do not count towards physical memory usage.", 
    "key": "tcmalloc.pageheap-unmapped-bytes", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "TCMalloc Pageheap Unmapped", 
    "units": Metrics.TUnit.BYTES
  }, 
  "tcmalloc.physical-bytes-reserved": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Derived metric computing the amount of physical memory (in bytes) used by the process, including that actually in use and free bytes reserved by tcmalloc. Does not include the tcmalloc metadata.", 
    "key": "tcmalloc.physical-bytes-reserved", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "TCMalloc Physical Bytes Reserved", 
    "units": Metrics.TUnit.BYTES
  }, 
  "tcmalloc.total-bytes-reserved": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Bytes of system memory reserved by TCMalloc.", 
    "key": "tcmalloc.total-bytes-reserved", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "TCMalloc Total Bytes Reserved", 
    "units": Metrics.TUnit.BYTES
  }, 
  "thread-manager.running-threads": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "The number of running threads in this process.", 
    "key": "thread-manager.running-threads", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Running Threads", 
    "units": Metrics.TUnit.NONE
  }, 
  "thread-manager.total-threads-created": {
    "contexts": [
      "STATESTORE", 
      "CATALOGSERVER", 
      "IMPALAD"
    ], 
    "description": "Threads created over the lifetime of the process.", 
    "key": "thread-manager.total-threads-created", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Threads Created", 
    "units": Metrics.TUnit.NONE
  }, 
  "tmp-file-mgr.active-scratch-dirs": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The number of active scratch directories for spilling to disk.", 
    "key": "tmp-file-mgr.active-scratch-dirs", 
    "kind": Metrics.TMetricKind.GAUGE, 
    "label": "Active scratch directories", 
    "units": Metrics.TUnit.NONE
  }, 
  "tmp-file-mgr.active-scratch-dirs.list": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "The set of all active scratch directories for spilling to disk.", 
    "key": "tmp-file-mgr.active-scratch-dirs.list", 
    "kind": Metrics.TMetricKind.SET, 
    "label": "Active scratch directories list", 
    "units": Metrics.TUnit.NONE
  }, 
  "total-senders-blocked-on-recvr-creation": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total number of senders that have been blocked waiting for receiving fragment to initialize.", 
    "key": "total-senders-blocked-on-recvr-creation", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Total senders waiting for receiving fragment to initialize", 
    "units": Metrics.TUnit.NONE
  }, 
  "total-senders-timedout-waiting-for-recvr-creation": {
    "contexts": [
      "IMPALAD"
    ], 
    "description": "Total number of senders that timed-out waiting for receiving fragment to initialize.", 
    "key": "total-senders-timedout-waiting-for-recvr-creation", 
    "kind": Metrics.TMetricKind.COUNTER, 
    "label": "Total senders timed-out waiting for receiving fragment to initialize", 
    "units": Metrics.TUnit.NONE
  }
}